//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSMVC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_master()
        {
            this.vehicle_details = new HashSet<vehicle_details>();
        }
    
        public int user_id { get; set; }
        public string name { get; set; }
        public string mobile_number { get; set; }
        public string organization { get; set; }
        public string address { get; set; }
        public string email_id { get; set; }
        public string location { get; set; }
        public string photopath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehicle_details> vehicle_details { get; set; }
    }
}
