//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSMVC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_details
    {
        public string vehicle_number { get; set; }
        public string vehicle_type { get; set; }
        public string chasis_number { get; set; }
        public string engine_number { get; set; }
        public string manufacturing_year { get; set; }
        public string load_carrying_capacity { get; set; }
        public string make_of_vehicle { get; set; }
        public string model_number { get; set; }
        public string body_type { get; set; }
        public string organization { get; set; }
        public Nullable<int> device_id { get; set; }
        public Nullable<int> id { get; set; }
    
        public virtual user_master user_master { get; set; }
    }
}
